# Generated by Django 5.1.7 on 2025-05-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexity',
            name='complexity',
            field=models.IntegerField(null=True),
        ),
    ]
