# Generated by Django 5.1.7 on 2025-05-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_complexity_complexity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexity',
            name='complexity',
            field=models.IntegerField(),
        ),
    ]
