# Generated by Django 5.1.7 on 2025-05-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_complexity_complexity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('classroom', 'Кабинет'), ('gym', 'Спортзал'), ('hall', 'Актовый зал'), ('tech', 'Кабинет технологии'), ('physics', 'Кабинет физики'), ('chemistry', 'Кабинет химии'), ('informatics', 'Кабинет информатики'), ('art', 'Кабинет ИЗО')], null=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
