# Generated by Django 5.1.7 on 2025-05-22 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д')])),
                ('student_amount', models.PositiveIntegerField()),
                ('eduparallel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiapp.eduparallel')),
                ('own_classroom', models.OneToOneField(default='Нет свого класса', on_delete=django.db.models.deletion.SET_DEFAULT, to='apiapp.classroom')),
            ],
        ),
    ]
