# Generated by Django 5.1.7 on 2025-05-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('eduparallels', models.ManyToManyField(to='apiapp.eduparallel')),
                ('subjects', models.ManyToManyField(to='apiapp.subject')),
            ],
        ),
    ]
