# Generated by Django 5.1.7 on 2025-05-30 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_schooluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexity',
            name='eduparallel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu_complexities', to='apiapp.eduparallel'),
        ),
        migrations.AlterField(
            model_name='complexity',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbj_complexity', to='apiapp.subject'),
        ),
    ]
