# Generated by Django 5.1.7 on 2025-05-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_alter_complexity_eduparallel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexity',
            name='hours_per_week',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='complexity',
            name='complexity',
            field=models.SmallIntegerField(),
        ),
    ]
