# Generated by Django 5.1.7 on 2025-06-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_complexity_hours_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='own_classroom',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='apiapp.classroom'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('eduparallel', 'letter'), name='unique_class'),
        ),
    ]
