# Generated by Django 5.1.7 on 2025-06-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_alter_class_own_classroom_class_unique_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='own_classroom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.classroom'),
        ),
    ]
