# Generated by Django 5.1.7 on 2025-06-08 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_alter_class_own_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduparallel',
            name='subjects',
            field=models.ManyToManyField(related_name='rel_parallels', through='apiapp.Complexity', to='apiapp.subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='own_classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.classroom'),
        ),
    ]
