# Generated by Django 5.1.7 on 2025-06-19 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_eduparallel_subjects_alter_class_own_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.class')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('class_id', 'subject_id', 'teacher_id'), name='unique_lesson')],
            },
        ),
    ]
