# Generated by Django 5.1.7 on 2025-06-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.teacher'),
        ),
    ]
