# Generated by Django 5.1.7 on 2025-05-31 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiapp', '0008_alter_complexity_eduparallel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_m', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_for_compl', to='apiapp.class')),
                ('complexity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compl_for_class', to='apiapp.complexity')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbj_for_teacher', to='apiapp.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_for_sbj', to='apiapp.teacher')),
            ],
        ),
    ]
