# Generated by Django 5.1.7 on 2025-06-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
